# Generated by Django 5.0.2 on 2024-03-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0003_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default='none'),
        ),
    ]
