# Generated by Django 5.0.2 on 2024-03-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0004_hotel_description_restaurant_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='img')),
                ('category', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('location', models.URLField()),
                ('description', models.TextField(default='none')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(default={'ac': False, 'bar': False, 'fitness_center': False, 'laundry': False, 'parking': False, 'pet_friendly': False, 'restaurant': False, 'room_service': False, 'spa': False, 'swimming_pool': False, 'tv': False, 'wifi': False}),
        ),
    ]
