# Generated by Django 5.0.2 on 2024-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0005_place_hotel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='img',
            field=models.ImageField(upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(upload_to='places'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(upload_to='restaurant'),
        ),
    ]
