# Generated by Django 5.0.2 on 2024-03-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0010_rename_rid_customer_cid_rename_rid_hotel_hid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hid',
            new_name='rid',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='pid',
            new_name='rid',
        ),
    ]
