# Generated by Django 5.0.2 on 2024-03-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0013_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='email',
            field=models.CharField(default='xyz', max_length=100),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='mobile',
            field=models.CharField(default='xyz', max_length=15),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='name',
            field=models.CharField(default='xyz', max_length=255),
        ),
    ]
