# Generated by Django 5.0.2 on 2024-03-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0015_tourguide_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='price',
            field=models.CharField(default='1000', max_length=25),
        ),
    ]
