# Generated by Django 5.0.2 on 2024-05-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0028_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feedback',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active'),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
