# Generated by Django 5.0.2 on 2024-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='img')),
                ('city', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('location', models.URLField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
