# Generated by Django 5.0.2 on 2024-03-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0009_alter_hotel_location_alter_place_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='rid',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='rid',
            new_name='hid',
        ),
    ]
