# Generated by Django 5.0.2 on 2024-03-11 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0011_rename_hid_hotel_rid_rename_pid_place_rid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField()),
                ('languages', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourguide.customer')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourguide.tourguide')),
            ],
        ),
    ]
