# Generated by Django 5.0.2 on 2024-03-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0014_tourguide_email_tourguide_mobile_tourguide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='password',
            field=models.CharField(default='xyz', max_length=500),
        ),
    ]
