# Generated by Django 5.0.2 on 2024-03-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0017_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
