# Generated by Django 5.0.2 on 2024-03-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0019_tourguide_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
