# Generated by Django 5.0.2 on 2024-03-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0020_tourguide_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguide',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
