# Generated by Django 5.0.2 on 2024-03-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0021_alter_tourguide_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguide',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active'),
        ),
    ]
