# Generated by Django 5.0.2 on 2024-03-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0024_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active'),
        ),
    ]
