# Generated by Django 5.0.2 on 2024-03-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0025_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
