# Generated by Django 5.0.2 on 2024-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0026_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
