# Generated by Django 5.0.2 on 2024-03-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0027_alter_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
