# Generated by Django 5.0.2 on 2024-05-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourguide', '0031_booking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
